package info.quiz.po;

import java.util.Date;

public class Problem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.taskBackground
     *
     * @mbg.generated
     */
    private String taskbackground;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.taskRequirement
     *
     * @mbg.generated
     */
    private String taskrequirement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.complexity
     *
     * @mbg.generated
     */
    private Integer complexity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.resourceType
     *
     * @mbg.generated
     */
    private Integer resourcetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.items
     *
     * @mbg.generated
     */
    private String items;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.answer
     *
     * @mbg.generated
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.subjectType
     *
     * @mbg.generated
     */
    private Integer subjecttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.operateTime
     *
     * @mbg.generated
     */
    private Date operatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.ID
     *
     * @return the value of problem.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.ID
     *
     * @param id the value for problem.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.taskBackground
     *
     * @return the value of problem.taskBackground
     *
     * @mbg.generated
     */
    public String getTaskbackground() {
        return taskbackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.taskBackground
     *
     * @param taskbackground the value for problem.taskBackground
     *
     * @mbg.generated
     */
    public void setTaskbackground(String taskbackground) {
        this.taskbackground = taskbackground == null ? null : taskbackground.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.taskRequirement
     *
     * @return the value of problem.taskRequirement
     *
     * @mbg.generated
     */
    public String getTaskrequirement() {
        return taskrequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.taskRequirement
     *
     * @param taskrequirement the value for problem.taskRequirement
     *
     * @mbg.generated
     */
    public void setTaskrequirement(String taskrequirement) {
        this.taskrequirement = taskrequirement == null ? null : taskrequirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.complexity
     *
     * @return the value of problem.complexity
     *
     * @mbg.generated
     */
    public Integer getComplexity() {
        return complexity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.complexity
     *
     * @param complexity the value for problem.complexity
     *
     * @mbg.generated
     */
    public void setComplexity(Integer complexity) {
        this.complexity = complexity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.resourceType
     *
     * @return the value of problem.resourceType
     *
     * @mbg.generated
     */
    public Integer getResourcetype() {
        return resourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.resourceType
     *
     * @param resourcetype the value for problem.resourceType
     *
     * @mbg.generated
     */
    public void setResourcetype(Integer resourcetype) {
        this.resourcetype = resourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.items
     *
     * @return the value of problem.items
     *
     * @mbg.generated
     */
    public String getItems() {
        return items;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.items
     *
     * @param items the value for problem.items
     *
     * @mbg.generated
     */
    public void setItems(String items) {
        this.items = items == null ? null : items.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.answer
     *
     * @return the value of problem.answer
     *
     * @mbg.generated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.answer
     *
     * @param answer the value for problem.answer
     *
     * @mbg.generated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.subjectType
     *
     * @return the value of problem.subjectType
     *
     * @mbg.generated
     */
    public Integer getSubjecttype() {
        return subjecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.subjectType
     *
     * @param subjecttype the value for problem.subjectType
     *
     * @mbg.generated
     */
    public void setSubjecttype(Integer subjecttype) {
        this.subjecttype = subjecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.operateTime
     *
     * @return the value of problem.operateTime
     *
     * @mbg.generated
     */
    public Date getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.operateTime
     *
     * @param operatetime the value for problem.operateTime
     *
     * @mbg.generated
     */
    public void setOperatetime(Date operatetime) {
        this.operatetime = operatetime;
    }
}