package info.quiz.po;

public class Rank {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.chineseName
     *
     * @mbg.generated
     */
    private String chinesename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.primaryScore
     *
     * @mbg.generated
     */
    private Double primaryscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.secondaryScore
     *
     * @mbg.generated
     */
    private Double secondaryscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.school
     *
     * @mbg.generated
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.institute
     *
     * @mbg.generated
     */
    private String institute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.major
     *
     * @mbg.generated
     */
    private String major;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.username
     *
     * @return the value of rank.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.username
     *
     * @param username the value for rank.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.chineseName
     *
     * @return the value of rank.chineseName
     *
     * @mbg.generated
     */
    public String getChinesename() {
        return chinesename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.chineseName
     *
     * @param chinesename the value for rank.chineseName
     *
     * @mbg.generated
     */
    public void setChinesename(String chinesename) {
        this.chinesename = chinesename == null ? null : chinesename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.primaryScore
     *
     * @return the value of rank.primaryScore
     *
     * @mbg.generated
     */
    public Double getPrimaryscore() {
        return primaryscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.primaryScore
     *
     * @param primaryscore the value for rank.primaryScore
     *
     * @mbg.generated
     */
    public void setPrimaryscore(Double primaryscore) {
        this.primaryscore = primaryscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.secondaryScore
     *
     * @return the value of rank.secondaryScore
     *
     * @mbg.generated
     */
    public Double getSecondaryscore() {
        return secondaryscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.secondaryScore
     *
     * @param secondaryscore the value for rank.secondaryScore
     *
     * @mbg.generated
     */
    public void setSecondaryscore(Double secondaryscore) {
        this.secondaryscore = secondaryscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.phone
     *
     * @return the value of rank.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.phone
     *
     * @param phone the value for rank.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.school
     *
     * @return the value of rank.school
     *
     * @mbg.generated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.school
     *
     * @param school the value for rank.school
     *
     * @mbg.generated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.institute
     *
     * @return the value of rank.institute
     *
     * @mbg.generated
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.institute
     *
     * @param institute the value for rank.institute
     *
     * @mbg.generated
     */
    public void setInstitute(String institute) {
        this.institute = institute == null ? null : institute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.major
     *
     * @return the value of rank.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.major
     *
     * @param major the value for rank.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }
}