package info.quiz.po;

import java.util.Date;

public class Record {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.problemIdList
     *
     * @mbg.generated
     */
    private String problemidlist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.startTime
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item1
     *
     * @mbg.generated
     */
    private String item1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time1
     *
     * @mbg.generated
     */
    private Double time1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item2
     *
     * @mbg.generated
     */
    private String item2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time2
     *
     * @mbg.generated
     */
    private Double time2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item3
     *
     * @mbg.generated
     */
    private String item3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time3
     *
     * @mbg.generated
     */
    private Double time3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item4
     *
     * @mbg.generated
     */
    private String item4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time4
     *
     * @mbg.generated
     */
    private Double time4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item5
     *
     * @mbg.generated
     */
    private String item5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time5
     *
     * @mbg.generated
     */
    private Double time5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item6
     *
     * @mbg.generated
     */
    private String item6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time6
     *
     * @mbg.generated
     */
    private Double time6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item7
     *
     * @mbg.generated
     */
    private String item7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time7
     *
     * @mbg.generated
     */
    private Double time7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item8
     *
     * @mbg.generated
     */
    private String item8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time8
     *
     * @mbg.generated
     */
    private Double time8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item9
     *
     * @mbg.generated
     */
    private String item9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time9
     *
     * @mbg.generated
     */
    private Double time9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item10
     *
     * @mbg.generated
     */
    private String item10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time10
     *
     * @mbg.generated
     */
    private Double time10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item11
     *
     * @mbg.generated
     */
    private String item11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time11
     *
     * @mbg.generated
     */
    private Double time11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item12
     *
     * @mbg.generated
     */
    private String item12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time12
     *
     * @mbg.generated
     */
    private Double time12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item13
     *
     * @mbg.generated
     */
    private String item13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time13
     *
     * @mbg.generated
     */
    private Double time13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item14
     *
     * @mbg.generated
     */
    private String item14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time14
     *
     * @mbg.generated
     */
    private Double time14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item15
     *
     * @mbg.generated
     */
    private String item15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time15
     *
     * @mbg.generated
     */
    private Double time15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item16
     *
     * @mbg.generated
     */
    private String item16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time16
     *
     * @mbg.generated
     */
    private Double time16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item17
     *
     * @mbg.generated
     */
    private String item17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time17
     *
     * @mbg.generated
     */
    private Double time17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item18
     *
     * @mbg.generated
     */
    private String item18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time18
     *
     * @mbg.generated
     */
    private Double time18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item19
     *
     * @mbg.generated
     */
    private String item19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time19
     *
     * @mbg.generated
     */
    private Double time19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.item20
     *
     * @mbg.generated
     */
    private String item20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time20
     *
     * @mbg.generated
     */
    private Double time20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.endTime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.sumTime
     *
     * @mbg.generated
     */
    private Double sumtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.timeScore
     *
     * @mbg.generated
     */
    private Double timescore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.subjectScore
     *
     * @mbg.generated
     */
    private Double subjectscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.sumScore
     *
     * @mbg.generated
     */
    private Double sumscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.round
     *
     * @mbg.generated
     */
    private Integer round;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.userId
     *
     * @return the value of record.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.userId
     *
     * @param userid the value for record.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.problemIdList
     *
     * @return the value of record.problemIdList
     *
     * @mbg.generated
     */
    public String getProblemidlist() {
        return problemidlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.problemIdList
     *
     * @param problemidlist the value for record.problemIdList
     *
     * @mbg.generated
     */
    public void setProblemidlist(String problemidlist) {
        this.problemidlist = problemidlist == null ? null : problemidlist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.startTime
     *
     * @return the value of record.startTime
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.startTime
     *
     * @param starttime the value for record.startTime
     *
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item1
     *
     * @return the value of record.item1
     *
     * @mbg.generated
     */
    public String getItem1() {
        return item1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item1
     *
     * @param item1 the value for record.item1
     *
     * @mbg.generated
     */
    public void setItem1(String item1) {
        this.item1 = item1 == null ? null : item1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time1
     *
     * @return the value of record.time1
     *
     * @mbg.generated
     */
    public Double getTime1() {
        return time1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time1
     *
     * @param time1 the value for record.time1
     *
     * @mbg.generated
     */
    public void setTime1(Double time1) {
        this.time1 = time1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item2
     *
     * @return the value of record.item2
     *
     * @mbg.generated
     */
    public String getItem2() {
        return item2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item2
     *
     * @param item2 the value for record.item2
     *
     * @mbg.generated
     */
    public void setItem2(String item2) {
        this.item2 = item2 == null ? null : item2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time2
     *
     * @return the value of record.time2
     *
     * @mbg.generated
     */
    public Double getTime2() {
        return time2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time2
     *
     * @param time2 the value for record.time2
     *
     * @mbg.generated
     */
    public void setTime2(Double time2) {
        this.time2 = time2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item3
     *
     * @return the value of record.item3
     *
     * @mbg.generated
     */
    public String getItem3() {
        return item3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item3
     *
     * @param item3 the value for record.item3
     *
     * @mbg.generated
     */
    public void setItem3(String item3) {
        this.item3 = item3 == null ? null : item3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time3
     *
     * @return the value of record.time3
     *
     * @mbg.generated
     */
    public Double getTime3() {
        return time3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time3
     *
     * @param time3 the value for record.time3
     *
     * @mbg.generated
     */
    public void setTime3(Double time3) {
        this.time3 = time3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item4
     *
     * @return the value of record.item4
     *
     * @mbg.generated
     */
    public String getItem4() {
        return item4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item4
     *
     * @param item4 the value for record.item4
     *
     * @mbg.generated
     */
    public void setItem4(String item4) {
        this.item4 = item4 == null ? null : item4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time4
     *
     * @return the value of record.time4
     *
     * @mbg.generated
     */
    public Double getTime4() {
        return time4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time4
     *
     * @param time4 the value for record.time4
     *
     * @mbg.generated
     */
    public void setTime4(Double time4) {
        this.time4 = time4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item5
     *
     * @return the value of record.item5
     *
     * @mbg.generated
     */
    public String getItem5() {
        return item5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item5
     *
     * @param item5 the value for record.item5
     *
     * @mbg.generated
     */
    public void setItem5(String item5) {
        this.item5 = item5 == null ? null : item5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time5
     *
     * @return the value of record.time5
     *
     * @mbg.generated
     */
    public Double getTime5() {
        return time5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time5
     *
     * @param time5 the value for record.time5
     *
     * @mbg.generated
     */
    public void setTime5(Double time5) {
        this.time5 = time5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item6
     *
     * @return the value of record.item6
     *
     * @mbg.generated
     */
    public String getItem6() {
        return item6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item6
     *
     * @param item6 the value for record.item6
     *
     * @mbg.generated
     */
    public void setItem6(String item6) {
        this.item6 = item6 == null ? null : item6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time6
     *
     * @return the value of record.time6
     *
     * @mbg.generated
     */
    public Double getTime6() {
        return time6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time6
     *
     * @param time6 the value for record.time6
     *
     * @mbg.generated
     */
    public void setTime6(Double time6) {
        this.time6 = time6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item7
     *
     * @return the value of record.item7
     *
     * @mbg.generated
     */
    public String getItem7() {
        return item7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item7
     *
     * @param item7 the value for record.item7
     *
     * @mbg.generated
     */
    public void setItem7(String item7) {
        this.item7 = item7 == null ? null : item7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time7
     *
     * @return the value of record.time7
     *
     * @mbg.generated
     */
    public Double getTime7() {
        return time7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time7
     *
     * @param time7 the value for record.time7
     *
     * @mbg.generated
     */
    public void setTime7(Double time7) {
        this.time7 = time7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item8
     *
     * @return the value of record.item8
     *
     * @mbg.generated
     */
    public String getItem8() {
        return item8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item8
     *
     * @param item8 the value for record.item8
     *
     * @mbg.generated
     */
    public void setItem8(String item8) {
        this.item8 = item8 == null ? null : item8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time8
     *
     * @return the value of record.time8
     *
     * @mbg.generated
     */
    public Double getTime8() {
        return time8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time8
     *
     * @param time8 the value for record.time8
     *
     * @mbg.generated
     */
    public void setTime8(Double time8) {
        this.time8 = time8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item9
     *
     * @return the value of record.item9
     *
     * @mbg.generated
     */
    public String getItem9() {
        return item9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item9
     *
     * @param item9 the value for record.item9
     *
     * @mbg.generated
     */
    public void setItem9(String item9) {
        this.item9 = item9 == null ? null : item9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time9
     *
     * @return the value of record.time9
     *
     * @mbg.generated
     */
    public Double getTime9() {
        return time9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time9
     *
     * @param time9 the value for record.time9
     *
     * @mbg.generated
     */
    public void setTime9(Double time9) {
        this.time9 = time9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item10
     *
     * @return the value of record.item10
     *
     * @mbg.generated
     */
    public String getItem10() {
        return item10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item10
     *
     * @param item10 the value for record.item10
     *
     * @mbg.generated
     */
    public void setItem10(String item10) {
        this.item10 = item10 == null ? null : item10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time10
     *
     * @return the value of record.time10
     *
     * @mbg.generated
     */
    public Double getTime10() {
        return time10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time10
     *
     * @param time10 the value for record.time10
     *
     * @mbg.generated
     */
    public void setTime10(Double time10) {
        this.time10 = time10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item11
     *
     * @return the value of record.item11
     *
     * @mbg.generated
     */
    public String getItem11() {
        return item11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item11
     *
     * @param item11 the value for record.item11
     *
     * @mbg.generated
     */
    public void setItem11(String item11) {
        this.item11 = item11 == null ? null : item11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time11
     *
     * @return the value of record.time11
     *
     * @mbg.generated
     */
    public Double getTime11() {
        return time11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time11
     *
     * @param time11 the value for record.time11
     *
     * @mbg.generated
     */
    public void setTime11(Double time11) {
        this.time11 = time11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item12
     *
     * @return the value of record.item12
     *
     * @mbg.generated
     */
    public String getItem12() {
        return item12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item12
     *
     * @param item12 the value for record.item12
     *
     * @mbg.generated
     */
    public void setItem12(String item12) {
        this.item12 = item12 == null ? null : item12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time12
     *
     * @return the value of record.time12
     *
     * @mbg.generated
     */
    public Double getTime12() {
        return time12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time12
     *
     * @param time12 the value for record.time12
     *
     * @mbg.generated
     */
    public void setTime12(Double time12) {
        this.time12 = time12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item13
     *
     * @return the value of record.item13
     *
     * @mbg.generated
     */
    public String getItem13() {
        return item13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item13
     *
     * @param item13 the value for record.item13
     *
     * @mbg.generated
     */
    public void setItem13(String item13) {
        this.item13 = item13 == null ? null : item13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time13
     *
     * @return the value of record.time13
     *
     * @mbg.generated
     */
    public Double getTime13() {
        return time13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time13
     *
     * @param time13 the value for record.time13
     *
     * @mbg.generated
     */
    public void setTime13(Double time13) {
        this.time13 = time13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item14
     *
     * @return the value of record.item14
     *
     * @mbg.generated
     */
    public String getItem14() {
        return item14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item14
     *
     * @param item14 the value for record.item14
     *
     * @mbg.generated
     */
    public void setItem14(String item14) {
        this.item14 = item14 == null ? null : item14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time14
     *
     * @return the value of record.time14
     *
     * @mbg.generated
     */
    public Double getTime14() {
        return time14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time14
     *
     * @param time14 the value for record.time14
     *
     * @mbg.generated
     */
    public void setTime14(Double time14) {
        this.time14 = time14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item15
     *
     * @return the value of record.item15
     *
     * @mbg.generated
     */
    public String getItem15() {
        return item15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item15
     *
     * @param item15 the value for record.item15
     *
     * @mbg.generated
     */
    public void setItem15(String item15) {
        this.item15 = item15 == null ? null : item15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time15
     *
     * @return the value of record.time15
     *
     * @mbg.generated
     */
    public Double getTime15() {
        return time15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time15
     *
     * @param time15 the value for record.time15
     *
     * @mbg.generated
     */
    public void setTime15(Double time15) {
        this.time15 = time15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item16
     *
     * @return the value of record.item16
     *
     * @mbg.generated
     */
    public String getItem16() {
        return item16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item16
     *
     * @param item16 the value for record.item16
     *
     * @mbg.generated
     */
    public void setItem16(String item16) {
        this.item16 = item16 == null ? null : item16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time16
     *
     * @return the value of record.time16
     *
     * @mbg.generated
     */
    public Double getTime16() {
        return time16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time16
     *
     * @param time16 the value for record.time16
     *
     * @mbg.generated
     */
    public void setTime16(Double time16) {
        this.time16 = time16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item17
     *
     * @return the value of record.item17
     *
     * @mbg.generated
     */
    public String getItem17() {
        return item17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item17
     *
     * @param item17 the value for record.item17
     *
     * @mbg.generated
     */
    public void setItem17(String item17) {
        this.item17 = item17 == null ? null : item17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time17
     *
     * @return the value of record.time17
     *
     * @mbg.generated
     */
    public Double getTime17() {
        return time17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time17
     *
     * @param time17 the value for record.time17
     *
     * @mbg.generated
     */
    public void setTime17(Double time17) {
        this.time17 = time17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item18
     *
     * @return the value of record.item18
     *
     * @mbg.generated
     */
    public String getItem18() {
        return item18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item18
     *
     * @param item18 the value for record.item18
     *
     * @mbg.generated
     */
    public void setItem18(String item18) {
        this.item18 = item18 == null ? null : item18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time18
     *
     * @return the value of record.time18
     *
     * @mbg.generated
     */
    public Double getTime18() {
        return time18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time18
     *
     * @param time18 the value for record.time18
     *
     * @mbg.generated
     */
    public void setTime18(Double time18) {
        this.time18 = time18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item19
     *
     * @return the value of record.item19
     *
     * @mbg.generated
     */
    public String getItem19() {
        return item19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item19
     *
     * @param item19 the value for record.item19
     *
     * @mbg.generated
     */
    public void setItem19(String item19) {
        this.item19 = item19 == null ? null : item19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time19
     *
     * @return the value of record.time19
     *
     * @mbg.generated
     */
    public Double getTime19() {
        return time19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time19
     *
     * @param time19 the value for record.time19
     *
     * @mbg.generated
     */
    public void setTime19(Double time19) {
        this.time19 = time19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.item20
     *
     * @return the value of record.item20
     *
     * @mbg.generated
     */
    public String getItem20() {
        return item20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.item20
     *
     * @param item20 the value for record.item20
     *
     * @mbg.generated
     */
    public void setItem20(String item20) {
        this.item20 = item20 == null ? null : item20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time20
     *
     * @return the value of record.time20
     *
     * @mbg.generated
     */
    public Double getTime20() {
        return time20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time20
     *
     * @param time20 the value for record.time20
     *
     * @mbg.generated
     */
    public void setTime20(Double time20) {
        this.time20 = time20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.endTime
     *
     * @return the value of record.endTime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.endTime
     *
     * @param endtime the value for record.endTime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.sumTime
     *
     * @return the value of record.sumTime
     *
     * @mbg.generated
     */
    public Double getSumtime() {
        return sumtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.sumTime
     *
     * @param sumtime the value for record.sumTime
     *
     * @mbg.generated
     */
    public void setSumtime(Double sumtime) {
        this.sumtime = sumtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.timeScore
     *
     * @return the value of record.timeScore
     *
     * @mbg.generated
     */
    public Double getTimescore() {
        return timescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.timeScore
     *
     * @param timescore the value for record.timeScore
     *
     * @mbg.generated
     */
    public void setTimescore(Double timescore) {
        this.timescore = timescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.subjectScore
     *
     * @return the value of record.subjectScore
     *
     * @mbg.generated
     */
    public Double getSubjectscore() {
        return subjectscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.subjectScore
     *
     * @param subjectscore the value for record.subjectScore
     *
     * @mbg.generated
     */
    public void setSubjectscore(Double subjectscore) {
        this.subjectscore = subjectscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.sumScore
     *
     * @return the value of record.sumScore
     *
     * @mbg.generated
     */
    public Double getSumscore() {
        return sumscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.sumScore
     *
     * @param sumscore the value for record.sumScore
     *
     * @mbg.generated
     */
    public void setSumscore(Double sumscore) {
        this.sumscore = sumscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.round
     *
     * @return the value of record.round
     *
     * @mbg.generated
     */
    public Integer getRound() {
        return round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.round
     *
     * @param round the value for record.round
     *
     * @mbg.generated
     */
    public void setRound(Integer round) {
        this.round = round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.count
     *
     * @return the value of record.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.count
     *
     * @param count the value for record.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}