package info.quiz.po;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.chineseName
     *
     * @mbg.generated
     */
    private String chinesename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.school
     *
     * @mbg.generated
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.institute
     *
     * @mbg.generated
     */
    private String institute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.major
     *
     * @mbg.generated
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isAdmin
     *
     * @mbg.generated
     */
    private Boolean isadmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.refreshCnt
     *
     * @mbg.generated
     */
    private Integer refreshcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.registerTime
     *
     * @mbg.generated
     */
    private Date registertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.round
     *
     * @mbg.generated
     */
    private Integer round;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.chineseName
     *
     * @return the value of user.chineseName
     *
     * @mbg.generated
     */
    public String getChinesename() {
        return chinesename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.chineseName
     *
     * @param chinesename the value for user.chineseName
     *
     * @mbg.generated
     */
    public void setChinesename(String chinesename) {
        this.chinesename = chinesename == null ? null : chinesename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.school
     *
     * @return the value of user.school
     *
     * @mbg.generated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.school
     *
     * @param school the value for user.school
     *
     * @mbg.generated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.institute
     *
     * @return the value of user.institute
     *
     * @mbg.generated
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.institute
     *
     * @param institute the value for user.institute
     *
     * @mbg.generated
     */
    public void setInstitute(String institute) {
        this.institute = institute == null ? null : institute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.major
     *
     * @return the value of user.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.major
     *
     * @param major the value for user.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq
     *
     * @return the value of user.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq
     *
     * @param qq the value for user.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mail
     *
     * @return the value of user.mail
     *
     * @mbg.generated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mail
     *
     * @param mail the value for user.mail
     *
     * @mbg.generated
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isAdmin
     *
     * @return the value of user.isAdmin
     *
     * @mbg.generated
     */
    public Boolean getIsadmin() {
        return isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isAdmin
     *
     * @param isadmin the value for user.isAdmin
     *
     * @mbg.generated
     */
    public void setIsadmin(Boolean isadmin) {
        this.isadmin = isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.refreshCnt
     *
     * @return the value of user.refreshCnt
     *
     * @mbg.generated
     */
    public Integer getRefreshcnt() {
        return refreshcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.refreshCnt
     *
     * @param refreshcnt the value for user.refreshCnt
     *
     * @mbg.generated
     */
    public void setRefreshcnt(Integer refreshcnt) {
        this.refreshcnt = refreshcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.registerTime
     *
     * @return the value of user.registerTime
     *
     * @mbg.generated
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.registerTime
     *
     * @param registertime the value for user.registerTime
     *
     * @mbg.generated
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.round
     *
     * @return the value of user.round
     *
     * @mbg.generated
     */
    public Integer getRound() {
        return round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.round
     *
     * @param round the value for user.round
     *
     * @mbg.generated
     */
    public void setRound(Integer round) {
        this.round = round;
    }
}